### ISSUE TITLE
Two domains lead to same app

### ISSUE THREAD

**Issue by kpennell** [wmluke/dokku-domains-plugin#12]
Hello.  I'm a newbie with a problem.  I truly believe I followed the dokku and domains-plugin instructions right.  I think I'm just missing something on assigning to domains.  Perhaps with a port.

I deployed two sample Node apps and they seem to have launched fine.

`CONTAINER ID        IMAGE                       COMMAND                CREATED             STATUS                      PORTS                     NAMES
9947b492c768        dokku/noderest:latest       /bin/bash -c '/start   4 seconds ago       Up 4 seconds                0.0.0.0:49154->5000/tcp   sharp_ptolemy       
c466d368aa02        ac37d44feb0a                /build/builder         30 seconds ago      Exited (0) 6 seconds ago                              loving_mcclintock   
eb0753770011        progrium/buildstep:latest   /bin/bash -c 'mkdir    30 seconds ago      Exited (0) 30 seconds ago                             silly_bohr          
12e3d5ee5efc        dokku/nodesamp:latest       /bin/bash -c '/start   3 minutes ago       Up 3 minutes                0.0.0.0:49153->5000/tcp   jolly_torvalds      
`

When I go to myip:49153 or myip:49154, the apps are working there fine.

So then I followed the instructions for doing the domains:

`
root@kyledokku:~# dokku domains:set nodesamp www.ahalearning.co
-----> Creating /home/dokku/nodesamp/DOMAINS
 * Reloading nginx configuration nginx                                                                                                                                                          [ OK ] 
root@kyledokku:~# ssh dokku@187.180.224.50 domains:set nodesamp www.ahalearning.co
 * Reloading nginx configuration nginx
   ...done.
root@kyledokku:~# dokku domains:set noderest www.kyleapennell.com
-----> Creating /home/dokku/noderest/DOMAINS
 * Reloading nginx configuration nginx                                                                                                                                                          [ OK ] 
root@kyledokku:~# ssh dokku@187.180.224.50 domains:set noderest www.kyleapennell.com
 * Reloading nginx configuration nginx
   ...done.

`

And both those seemed to work fine.

So when I go `docker ps -a` , here's what I see:

`
CONTAINER ID        IMAGE                       COMMAND                CREATED             STATUS                      PORTS                     NAMES
9947b492c768        dokku/noderest:latest       /bin/bash -c '/start   9 minutes ago       Up 9 minutes                0.0.0.0:49154->5000/tcp   sharp_ptolemy       
c466d368aa02        ac37d44feb0a                /build/builder         10 minutes ago      Exited (0) 10 minutes ago                             loving_mcclintock   
eb0753770011        progrium/buildstep:latest   /bin/bash -c 'mkdir    10 minutes ago      Exited (0) 10 minutes ago                             silly_bohr          
12e3d5ee5efc        dokku/nodesamp:latest       /bin/bash -c '/start   13 minutes ago      Up 13 minutes               0.0.0.0:49153->5000/tcp   jolly_torvalds   
`

When I go to either of those domains, they both go to the app that was deployed second.  I'm seeing that `>5000`...does that mean they are both going to port 5000?  Is that where I'm going wrong?

Any other ideas on where to look or what to try?

**Comment by Antonhansel** [comment]
Hello @kpennell , since v0.3.1 Dokku has its own domain management built-in plugin.
The awesome plugin done by @wmluke actually breaks my apps since the new dokku versions.

To configure your domain with the built in plugin, read this http://progrium.viewdocs.io/dokku/nginx

Have a good day :)

**Comment by kpennell** [comment]
Thanks, Anton.

**Comment by wmluke** [comment]
Closing b/c #15
