### ISSUE TITLE
Deprecate plugin

### ISSUE THREAD

**Issue by angusfretwell** [wmluke/dokku-domains-plugin#15]
v0.3.10 of Dokku added a native domain management plugin. I've found that this plugin actually breaks deployment of apps on newer versions of Dokku. Would be good if you could add a warning about this in the README.

Thanks for making this awesome plugin, though. It served me well until domains became a standard feature of Dokku :smile_cat:

**Comment by DenisIzmaylov** [comment]
Could you please explain? I didn't found any related information about 'native' plugin.

**Comment by blakeembrey** [comment]
@DenisIzmaylov I've been using the latest version of Dokku and it exists for me. 

```
    domains:add <app> DOMAIN                        Add a custom domain to app
    domains <app>                                   List custom domains for app
    domains:clear <app>                             Clear all custom domains for app
    domains:remove <app> DOMAIN                     Remove a custom domain from app
```

**Comment by marblegravy** [comment]
Can anyone provide some uninstall instructions? I think this may be the cause of my current deploy dramas.

**Comment by wmluke** [comment]
Thanks for the heads up guys.  I will add a deprecation notice to the readme.

## To Uninstall 

Remove the following files:

* `/etc/nginx/conf.d/dokku-domains.conf`
* `/home/dokku/*/nginx-domains.conf`

Something like this should work, but I have NOT tested...

```bash
$ rm /etc/nginx/conf.d/dokku-domains.conf
$ find /home/dokku -wholename '*/nginx-domains.conf' -delete
```

Additionally, it [looks](https://github.com/progrium/dokku/blob/master/Makefile#L43) like that upon upgrading the new built-in `domains` plugin will replace this deprecated `domains` plugin, but you should verify that everything looks [right](https://github.com/progrium/dokku/tree/master/plugins/domains) in `/var/lib/dokku/plugins/domains` ie `PLUGINS_PATH`.

Please comment in this thread, how well this works for you or how your mileage varies.

Thanks,
Luke

**Comment by josegonzalez** [comment]
@wmluke Note, this and other plugins were the inspiration for the official version. There are some things we feel make dokku a great tool out of the box, and domain handling is one of them. Thanks for all your hard work!

**Comment by wmluke** [comment]
Hey @josegonzalez,

Thanks for the shoutout.  In all honesty, I suspected that my simple plugin wasn't keeping up with the needs of users, so I was very pleased to see a `domains` like plugin built into `0.3.10`.  The new built-in support looks great!

Cheers,
Luke
